---
- hosts: all
  roles:
    - role: andrewrothstein.anaconda
    - role: '{{playbook_dir}}'
      jupyter_supervisord_name: jupyter-supervisord-test
      jupyter_supervisord_environment: jupyter-supervisord-test-environment.yml
      
