---
- name: resolve jupyter-notebook run script
  become: '{{jupyter_supervisord_privilege_escalate}}'
  become_user: root
  with_items:
    - d: /usr/local/bin
      f: run-jupyter-notebook.sh
      m: '0755'
  template:
    src: '{{item.f}}.j2'
    dest: '{{item.d}}/{{item.f}}'
    mode: '{{item.m}}'
