---
- name: resolve jupyter-notebook run script
  become: yes
  become_user: root
  with_items:
    - usr/local/bin/run-jupyter-notebook.sh
  template: >
    src={{item}}.j2
    dest=/{{item}}
    mode=0755
